// CivOne
//
// To the extent possible under law, the person who associated CC0 with
// CivOne has waived all copyright and related or neighboring rights
// to CivOne.
//
// You should have received a copy of the CC0 legalcode along with this
// work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

namespace CivOne
{
	internal static partial class SDL
	{
		private enum SDL_PixelFormatEnum : uint
		{
			SDL_PIXELFORMAT_UNKNOWN,
			SDL_PIXELFORMAT_INDEX1LSB,
			SDL_PIXELFORMAT_INDEX1MSB,
			SDL_PIXELFORMAT_INDEX4LSB,
			SDL_PIXELFORMAT_INDEX4MSB,
			SDL_PIXELFORMAT_INDEX8,
			SDL_PIXELFORMAT_RGB332,
			SDL_PIXELFORMAT_RGB444,
			SDL_PIXELFORMAT_RGB555,
			SDL_PIXELFORMAT_BGR555,
			SDL_PIXELFORMAT_ARGB4444,
			SDL_PIXELFORMAT_RGBA4444,
			SDL_PIXELFORMAT_ABGR4444,
			SDL_PIXELFORMAT_BGRA4444,
			SDL_PIXELFORMAT_ARGB1555,
			SDL_PIXELFORMAT_RGBA5551,
			SDL_PIXELFORMAT_ABGR1555,
			SDL_PIXELFORMAT_BGRA5551,
			SDL_PIXELFORMAT_RGB565,
			SDL_PIXELFORMAT_BGR565,
			SDL_PIXELFORMAT_RGB24,
			SDL_PIXELFORMAT_BGR24,
			SDL_PIXELFORMAT_RGB888,
			SDL_PIXELFORMAT_RGBX8888,
			SDL_PIXELFORMAT_BGR888,
			SDL_PIXELFORMAT_BGRX8888,
			SDL_PIXELFORMAT_ARGB8888,
			SDL_PIXELFORMAT_RGBA8888,
			SDL_PIXELFORMAT_ABGR8888,
			SDL_PIXELFORMAT_BGRA8888,
			SDL_PIXELFORMAT_ARGB2101010,
			SDL_PIXELFORMAT_RGBA32,
			SDL_PIXELFORMAT_ARGB32,
			SDL_PIXELFORMAT_BGRA32,
			SDL_PIXELFORMAT_ABGR32,
			SDL_PIXELFORMAT_YV12,
			SDL_PIXELFORMAT_IYUV,
			SDL_PIXELFORMAT_YUY2,
			SDL_PIXELFORMAT_UYVY,
			SDL_PIXELFORMAT_YVYU,
			SDL_PIXELFORMAT_NV12,
			SDL_PIXELFORMAT_NV21
		}
	}
}